### ISSUE TITLE
Courses footer is showing default links

### ISSUE THREAD

**Issue by jtopjian** [overhangio/indigo#1]
First, thank you for releasing this theme - the timing was perfect for us.

We edited the `config.yml` file appropriately, rendered, and deployed. Upon verifying if the site looked correct, we noticed that the the links at `/courses/<name>/course/` were showing the default links. 

I'm not sure the best way to resolve this, but I have a patch which worked for us. I'll open a PR with it.

**Comment by regisb** [comment]
Closed by https://github.com/overhangio/indigo/pull/2
