### ISSUE TITLE
Spacing error

### ISSUE THREAD

**Issue by oedx2** [overhangio/indigo#14]
I believe there's an error where the spacing is inconsistent after every 4th class added. See screenshots here:

https://discuss.overhang.io/t/indigo-theme-spacing-error/1752

(FWIW spacing is consistent when not using Indigo and just using the Open edX default theme. Also I'm using Koa not Lilac)

I would also note that if I'm signed in and go to the "Discover New" page (i.e. lms.com/courses), the spacing is consistent. It's only when signed out and going to the main website landing page that this is inconsistent (which is of course a problem for the site looking good for new visitors)

**Comment by oedx2** [comment]
Apparently a workaround that one of my twitter followers found is to add

.courses .courses-listing {
  display: flex;
  flex-wrap: wrap;
  justify-content: center;
}

to indigo/theme/lms/static/sass/partials/lms/theme/_extras.scss

**Comment by regisb** [comment]
Thanks for the report @oedx2! Your indications were very useful.
