### ISSUE TITLE
How to customize the template

### ISSUE THREAD

**Issue by alothman-a** [overhangio/indigo#19]
Hello all, 

First, thank you for your huge effort. I'm new to Open Edx and I want to know how to customize the pages for example the main page? 
Is it necessary to build the image each time I change something in the template or the sass files? 
Also, I have a question about how to access the front-end components?

**Comment by regisb** [comment]
Please don't use Github issues for feature requests or for support. Instead, you should create a new topic in the official Tutor forums: https://discuss.overhang.io.

The process for contributing to the platform is described in the docs:
https://docs.tutor.overhang.io/tutor.html#contributing

For your particular issue, you will have to check this section of the docs: https://docs.tutor.overhang.io/tutorials/theming.html
