### ISSUE TITLE
Where to add and update custom static pages in Indigo?

### ISSUE THREAD

**Issue by Djas2017** [overhangio/indigo#4]
Hi,

Created the file indigo/config-custom.yml following the instructions in the section "Setting custom values" https://github.com/overhangio/indigo

`INDIGO_FOOTER_NAV_LINKS:
  - title: "About Us"
    url: "/about"
  - title: "Contact Us"
    url: "/contact"
  - title: "Our Services"
    url: "/services"`

Now, I cannot find where do I have to add the content of the pages: /about, /contact and /services?

**Comment by regisb** [comment]
This is actually a very good question! (although I usually prefer if questions are asked in the [forums](https://discuss.overhang.io), rather than in Github issues)

To answer your question I updated the README and added some static templates to override the about, contact and tos pages.
